plugins {
    id 'java-library'
    id 'com.palantir.git-version' version '0.13.0'
}

archivesBaseName = 'lll'
version = versionDetails().lastTag

java {
	sourceCompatibility = targetCompatibility = JavaVersion.VERSION_1_8
	withSourcesJar()
	withJavadocJar()
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.ow2.asm:asm-commons:9.7'
    implementation 'org.ow2.asm:asm-util:9.7'
}
